### ISSUE TITLE
error with NPM install - installing ddp-client

### ISSUE THREAD

**Issue by funkyeah** [spencercarli/react-native-meteor-boilerplate#10]
I've been reading through the blog posts and just did a fresh install of this repo hopefully following the instructions correctly. I ran into an issue with the npm install step after going into the RNApp folder.

I get the error:

```
Error: No compatible version found: ddp-client@'spencercarli/node-ddp-client'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1-beta1","0.1.1-beta2","0.1.1-beta3","0.1.1","0.1.2"]
```

Changing the version on this line to 0.1.2 seems to have worked for the moment:
https://github.com/spencercarli/react-native-meteor-boilerplate/blob/master/RNApp/package.json#L10

Is this a step that should be part of the instructions? is 0.1.2 OK?

**Comment by spencercarli** [comment]
Hey just gave this a shot and didn't experience an issue. Did you change anything in the app prior to running npm install?

**Comment by funkyeah** [comment]
No I didn't change anything, literally just cloned and ran the steps in the instructions.

Is `spencercarli/node-ddp-client` in the version field of `package.json` valid? 

I am relatively new to the NPM ecosystem so forgive me if this is stupid but maybe that works for you because you have https://github.com/spencercarli/node-ddp-client checked out locally?

**Comment by spencercarli** [comment]
That's really weird. I find NPM a bit tricky but that should be valid (see [here](https://docs.npmjs.com/files/package.json#github-urls).

I don't currently have `node-ddp-client` checked out on this machine so I don't think that's playing into it.

What version of npm are you using? If nothing else (i'll be going offline soon) use `ddp-client@0.1.1`. It's functional - there's just a reconnect bug that I had to fix which shouldn't effect you in development at least.

**Comment by funkyeah** [comment]
Your suspcicion was correct. I had run npm update but for some reason it didn't take. http://askubuntu.com/questions/562417/how-do-you-update-npm-to-the-latest-version

My version was older than 1.1.65 though so not sure why exactly it failed.

Either way updating npm and re-running npm install fixed everything.

**Comment by spencercarli** [comment]
Glad to hear you got it sorted out!
