### ISSUE TITLE
running on android device (with linux)

### ISSUE THREAD

**Issue by funkyeah** [spencercarli/react-native-meteor-boilerplate#11]
You asked about running on an Android device in the README. I have done that and recorded my steps that I would be happy to submit to the README. One catch though is that I did all this on a linux machine. In linux the steps for setting up your phone, installing the app on the device, and running the react native server are all a bit different than with XCODE on a mac.

Wondering if you want to keep the instructions mac only or how you want to handle mixing linux and mac instructions.

Here's the steps I wrote down. Let me know how you would change it or feel free to modify and add to the README as you see fit.
##### Enable USB Debugging

Enable USB Debugging on your phone. If already connected to your computer unplug and replug the USB connection afterwards. Android 5 steps below:

> Settings > About Phone > Build number > Tap it 7 times to become developer;
> Settings > Developer Options > USB Debugging.
##### Setup Device on Linux

Configure how the device will connect to the meteor server. See [running android on a device](https://facebook.github.io/react-native/docs/running-on-device-android.html) to pick from the options.

Plug in your device and use _lusb_ to find the first 4 digits of  your device ID.

> lsusb
> Bus 001 Device 003: ID 04e8:2e76 Motorola PCS

Enter this in udev rules. In the example we are copying over `04e8`

> echo SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", MODE="0666", GROUP="plugdev" | sudo tee /etc/udev/rules.d/51-android-usb.rules

Check that your device is properly connecting to ADB, the Android Debug Bridge, by using:

> adb devices

These steps are abstracted from the pages [running on device](https://facebook.github.io/react-native/docs/running-on-device-android.html) and [getting started](https://facebook.github.io/react-native/docs/getting-started-linux.html#setting-up-an-android-device) on linux. 
##### Install App and Run on Device for Linux

Build and install on your device, launch the react server, and then launch the app on your phone:

> react-native android
> react-native run-android

**Comment by spencercarli** [comment]
Thanks for this!! I would love to have instructions with Linux included. I recently got an Android device to work with so I can handle the mac side of things.

Would you mind opening a PR for this? Want to make sure you get the proper credit for this contribution! 😄

**Comment by funkyeah** [comment]
Submitted the pull request...  its only like my second pull request ever so I'd appreciate any feedback on how I should do them better

**Comment by spencercarli** [comment]
Thanks! Tracking this in #12 now
