### ISSUE TITLE
Meteor 1.3 DDP login

### ISSUE THREAD

**Issue by yohanology** [spencercarli/react-native-meteor-boilerplate#13]
Any ideas how to make the boilerplate work with Meteor 1.3 and the new directory structure? It seems the ddp login methods doesn't work anymore...

**Comment by yohanology** [comment]
Sorry my mistake, it's working well. Thanks again for this awesome boilerplate!!

**Comment by chrise86** [comment]
I keep getting `"error.accounts.Login forbidden [403]"` when logging in, any ideas? I know the username/email and password are correct as they work fine when executed within the Meteor app, even inside a client side browser console.

**Comment by spencercarli** [comment]
@chrise86 I haven't seen that issue before (when using proper credentials). What version of React Native, Meteor, and `react-native-meteor` are you using?

**Comment by chrise86** [comment]
```
react: 15.4.2,
react-native: 0.41.2,
react-native-meteor: 1.0.3
```

**Comment by chrise86** [comment]
So I'm just gonna hang my head in shame... It looks like my original call to `Meteor.loginWithPassword` had a typo, then when I rewrote the function to use the private method `Meteor._login` I corrected the typo; switching back to the previous `Meteor.loginWithPassword` is now working 🙈  sorry to trouble you

**Comment by spencercarli** [comment]
Typos, the bane of a developers existence 😄 Glad you got it sorted out!
