### ISSUE TITLE
Application RNApp has not been registered

### ISSUE THREAD

**Issue by hyperh** [spencercarli/react-native-meteor-boilerplate#14]
I cloned the repo and I tried to run the Android RNApp on my device and I got the following error:

```
Application RNApp has not been registered.
This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
```

Not understanding this, because I can see 

```
AppRegistry.registerComponent('RNApp', () => App);
```

in `index.android.js`.

Edit: Actually getting another error now, can't seem to replicate the first one:

```
undefined is not a function (evaluating 'EventPluginHub.injection.injectInstanceHandle(ReactInstanceHandles)')
```

Also as a side note, I followed your tutorials 1-3 listed here http://blog.differential.com/react-native-meteor-boilerplate/, and I didn't run into any problems there. I did notice the tutorials used `ddp-client` and the boilerplate uses `node-ddp-client`. Not sure if that's the issue.

**Comment by spencercarli** [comment]
Hmm thanks for bringing this up! I made some upgrades to the boilerplate last night and may have broken something - I'll try to look at it tonight.

In the mean time maybe try to downgrade react native to 0.23.X? I've experienced some issues on 0.24 on other projects.

**Comment by spencercarli** [comment]
Okay should be fixed. Was a series of silly mistakes on my end yesterday 😄

**Comment by hyperh** [comment]
Can confirm that this issue has been fixed. Thanks a lot!
