### ISSUE TITLE
What about auth with facebook, Twitter, etc?

### ISSUE THREAD

**Issue by faceyspacey** [spencercarli/react-native-meteor-boilerplate#2]
The react native simple auth package works well, perhaps it's just a matter of gathering the information received from it and passing it over DDP.

**Comment by spencercarli** [comment]
Would be something interesting! I'm not sure how oauth via Meteor works so I would have to do some digging.

I'm not sure that it would live in this repo or if it would be part of a ddp client module that we use in this repo. Regardless, it's on my radar! Thanks for opening the issue.

**Comment by josephdburdick** [comment]
I'm also very curious about these oauth topics.

**Comment by ghost** [comment]
+1

**Comment by duataud** [comment]
Maybe this could help but I can't integrate it. I hope you can. https://github.com/martijnwalraven/meteor-ios/issues/10

**Comment by spencercarli** [comment]
Hey all - I just wanted to drop a quick update regarding this. I've worked on Google Oauth for a client and am working on turning my learnings into a blog post. It's turned into a monster of a blog post and I'm running into some issues with Android (Android is still very foreign to me) so it may take a little bit longer.

If you're interested the repo is here: https://github.com/spencercarli/react-native-meteor-google-oauth

There's no specific documentation there - that will all come with the blog post. But if anyone is blocked and waiting to see how it can be done then maybe looking at the source code of that repo may help.

I hope to have the detailed blog post out soon!

**Comment by faceyspacey** [comment]
nice!

...lookin at: https://github.com/spencercarli/react-native-meteor-google-oauth/blob/dcb3c3f891795fad95a4e4bede5e0525756c42f9/RNApp/app/ddp.js#L97

it seems you use the same google auth request for both login and signup? I only ask because the signup method doesn't exist and I've done the same thing, i.e. just one button for both signup and login. I'm assuming you did that for initial demonstration purposes. 

...I'm about to implement this for Twitter, so it seems as far as interfacing with Meteor, you just have to get the `params` correct--would you say that's the case? What are the params exactly?

```
let params = { 
   twitter: {
      ???: '???',
      ???: '???',
      ???: '???',
   } 
};
```

Last thing: my plan is to use this multi-auth react native package to get the tokens: https://github.com/adamjmcgrath/react-native-simple-auth

it seems that if we plugged this in, we could get a bunch of auths all at once. Do you think it's as simple as using that, getting the correct tokens, and then passing them to `ddpClient.call("login",` ??

**Comment by spencercarli** [comment]
You're correct that it uses the same method for sign up and login. That's the pattern I saw with the meteor core packages and seems to be the norm with oauth. You can see how I'm looking up if a user exists from the [meteor package](https://github.com/spencercarli/meteor-accounts-google-oauth/blob/master/google.js#L55).

I'm not sure what all would be needed for Twitter but I would suggest reviewing source for the [`accounts-twitter`](https://github.com/meteor/meteor/tree/devel/packages/accounts-twitter) and the [`twitter`](https://github.com/meteor/meteor/tree/devel/packages/twitter) as well as reading the official Twitter docs.

`react-native-simple-auth` looks nice and I definitely want to do some deeper research into it. The other major oauth providers are on my list to do further research and document how to get them set up but I don't have a timeline for that yet.

**Comment by chrbradley** [comment]
@faceyspacey are you using https://github.com/adamjmcgrath/react-native-simple-auth yet? Just curious how you're managing the configuration object.

Any concerns with sending secrets to the device?

**Comment by spencercarli** [comment]
Oauth with facebook: https://medium.com/@spencer_carli/react-native-meteor-oauth-with-facebook-3d1346d7cdb7#.pnzlwbt76

Due to the complexities involved with setting up the native dependencies it is not something I'll be adding to the boilerplate.
