### ISSUE TITLE
Question about propTypes?

### ISSUE THREAD

**Issue by PolGuixe** [spencercarli/react-native-meteor-boilerplate#25]
What are these lines doing?

```
ProfileContainer.propTypes = {
  user: React.PropTypes.object,
};
```

**Comment by donedgardo** [comment]
It tells the `ProfileConatiner` class that it expects a property.
In this case its saying the property named `user` should be of `object` type.

Its validation, helps to mix and match components with an extra layer of reassurance and debugging.
