### ISSUE TITLE
Get list data from meteor collection and pass it to dataSource

### ISSUE THREAD

**Issue by sepehrooo** [spencercarli/react-native-meteor-boilerplate#26]
Hi,
I wanted to subscribe to a collection in my meteor app called "items", then pass it's data to a < ListView / >.
Can you please tell me the way to do so. I did a Meteor.subscribe('items'); and the ready() function returns false.

Also if you could update the todoApp with your updated boilerplate. It would be a great example on how to use the boilerplate.

**Comment by Umar-Abbas** [comment]
@sepehrooo you can find a good example in this pull request.

https://github.com/spencercarli/react-native-meteor-boilerplate/pull/27
https://github.com/spencercarli/react-native-meteor-boilerplate/pull/27/commits/7d8ce60c72a298c610f6b45346ed8415c463f8d9

**Comment by sepehrooo** [comment]
Thanks a lot @Umar-Abbas
