### ISSUE TITLE
Method "userCreate" undefined.

### ISSUE THREAD

**Issue by smooJitter** [spencercarli/react-native-meteor-boilerplate#28]
I'm running the example app and I'm getting this message from the start.  Do I need to create addition server side code.

**Comment by Wil-Ho** [comment]
The meteor side is under example/MeteorApp. So no need to create new code, just run "meteor".

I don't remember getting this error message. But like I said it should be pretty easy to get up and going.

**Comment by armandomendivil** [comment]
You don't need add code on server side for user accounts, when you add the accounts-password package it creates those endpoint by default "createUser", "login", etc. etc. but if you want know what happens you can use the code on the server side below and verify if the communication works well
`Accounts.onCreateUser(function(options, user) {
  return user;
});`

**Comment by smooJitter** [comment]
I see the accounts-base does not include password functionality. Thank you @armandomendivil

**Comment by spencercarli** [comment]
Sorry for the radio silence (in the middle of moving). Does the boilerplate not include the `accounts-password` package?
