### ISSUE TITLE
Consider different DDP client

### ISSUE THREAD

**Issue by spencercarli** [spencercarli/react-native-meteor-boilerplate#3]
One of the top confusions I've seen lately has been surrounding `ddp-client`. There also may be some issues related to reconnection in the package.

Need to look for alternatives and/or rebuild `ddp-client`.

**Comment by ghost** [comment]
Anything else you're considering in place of `ddp-client`?

**Comment by spencercarli** [comment]
Haven't done any digging yet but possible alternatives: 
- https://www.npmjs.com/package/ddp / https://www.npmjs.com/package/xolvio-ddp
- https://www.npmjs.com/package/react-native-meteor

Honestly though I'm leaning towards fixing the bugs in `ddp-client`, improving documentation, and removing minimongo-cache. I like how simple `ddp-client` is.

**Comment by spencercarli** [comment]
Work in progress. No minimongo-cache dependency and the reconnect bug should be fixed.

**Comment by spencercarli** [comment]
Sticking with the current solution until `react-native-meteor` is ready for prime time.
