### ISSUE TITLE
Please update deprecated packages.

### ISSUE THREAD

**Issue by sepehrooo** [spencercarli/react-native-meteor-boilerplate#30]
Hi,
When running npm install in RNApp folder, I'll get 2 warning messages which can be resolved by updating their packages in this project.

*_npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
*_npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!

npm WARN prefer global babel@5.8.38 should be installed with -g

**Comment by spencercarli** [comment]
I'm in the middle of moving so I may not be able to get to this soon but it's very likely npm packages are out of date. i would accept a PR w/ updates!

**Comment by bento-n-box** [comment]
+1

**Comment by spencercarli** [comment]
Updated in #39!
