### ISSUE TITLE
Unable to resolve module mobx

### ISSUE THREAD

**Issue by sepehrooo** [spencercarli/react-native-meteor-boilerplate#31]
I tried to react-native run-ios or run-android in RNApp and I get this error:
<img width="1060" alt="screen shot 2016-07-09 at 5 39 22 am" src="https://cloud.githubusercontent.com/assets/2351478/16705188/e1a04582-4597-11e6-8766-af7822ed51c0.png">
<img width="376" alt="screen shot 2016-07-09 at 5 39 17 am" src="https://cloud.githubusercontent.com/assets/2351478/16705190/e44b69c4-4597-11e6-9e93-ff313e651bba.png">

Please help me to resolve this issue.

**Comment by sepehrooo** [comment]
And I did npm install...

**Comment by spencercarli** [comment]
mobx isn't part of this boilerplate and I've never personally used it so I can't help much in debugging it. However do try to restart the react native packager. Otherwise open an issue over at [mobx](https://github.com/mobxjs/mobx).

Thanks!
