### ISSUE TITLE
Calling external meteor packages from react native

### ISSUE THREAD

**Issue by kayrules** [spencercarli/react-native-meteor-boilerplate#34]
Sorry, this should not be an issue for this awesome repo. But I dont know where to ask.

Im adding a package in meteor app as below:
`meteor add typ:accounts-ldap`

So now, how can I make a call to client method from react native. In plain meteor project, I can simply call the method from client code as below:

```
Meteor.loginWithLDAP(loginId, password, {
    dn: domain + '\\' + loginId,
    search: '(sAMAccountName=' + loginId + ')'
}, function(err) {
        if (err) console.log(err);
});
```

Tried using the same code in react native, but there's an error `loginWithLDAP` method is undefined.

pls help. thanks

**Comment by spencercarli** [comment]
So `Meteor.loginWithLDAP` is coming from the atmosphere package, hence the reason it doesn't work on React Native. What you'll have to do is recreate the client side file that's created by the package [here](https://github.com/etyp/meteor-accounts-ldap/blob/master/ldap_client.js).

I think it would end up looking something like

``` javascript
const loginData = {
  username: user,
  ldapPass: password
}, {
  ldap: true,
  ldapOptions: customLdapOptions
};
Meteor.call('login', loginData, (err, res) => {

});
```

Maybe it would be better to open an issue on the [`react-native-meteor`](https://github.com/inProgress-team/react-native-meteor) repo to get better info on how to extend the accounts system?

**Comment by kayrules** [comment]
thanks @spencercarli 
I have [forked the react-native-meteor](https://github.com/kayrules/react-native-meteor) repo and end-up with the following codes:

https://github.com/kayrules/react-native-meteor/blob/master/src/user/User.js#L58-L73

```
loginWithLDAP(userId, password, customLdapOptions, callback) {
    this._startLoggingIn();
    var loginRequest = {
        username: userId,
        ldapPass: password,
        ldap: true,
        ldapOptions: customLdapOptions
    };
    call("login", loginRequest, (err, result)=>{
      this._endLoggingIn();

      this._handleLoginCallback(err, result);

      typeof callback == 'function' && callback(err);
    });
  },
```

**Comment by spencercarli** [comment]
Nice! I think `react-native-meteor` is developed in a way so that you can extend the functionality (rather than having to fork it). Not sure how but I think you could make a package like `react-native-meteor-accounts-ldap` w/ your logic
