### ISSUE TITLE
Auto-reload? (Windows 10, Genymotion)

### ISSUE THREAD

**Issue by ghost** [spencercarli/react-native-meteor-boilerplate#36]
First off: Hi! great starter kit!
... but :)

Can you tell me how I can get Genymotion to automatically show the changes I made ?
At the moment I have to stop the React Packager and restart it (via react-native start)

My system:
Windows 10, Genymotion 2.7.2
"this" boilerplate from about 10. july 2016

Greetings from Germany,
Max

**Comment by mlumbroso** [comment]
Hi,
either press twice "R", or open Dev menu using CTRL+M and either press reload JS or better "Enable hot reloading".
:-)

**Comment by ghost** [comment]
tried all that many times :)

**Comment by spencercarli** [comment]
Hey Max, I'm not sure I can give much more advice that what @mlumbroso suggested. Does the developer menu open up for you? I wonder if this is a windows specific issue?

**Comment by mlumbroso** [comment]
Using Windows 10 + Genymotion the exact same way I described, what device are you using?

**Comment by ghost** [comment]
Yes: the developer menu opens up and i have tried some combinations. Changing to "hot reload" works only the first time. 

Device: Google Nexus 7 2013 - 6.0.0 - API 23 - 1200x1920

**Comment by mlumbroso** [comment]
For me on Nexus 5 and Nexus 5X hot reloading works great. Sorry I can't help more...
When you change code you don't see the "Hot loading..." label?

**Comment by spencercarli** [comment]
Does the app crash? I just worked through an issue where an android app was crashing after a hot reload. Ended up being a memory error due to some massive images

**Comment by ghost** [comment]
no it doesnt crash. it just doesnt reload automatically...

I switched to "Google Nexus 5  - 5.0.0 - API 21 -  1080x1920" but it still doesnt work :(

**Comment by spencercarli** [comment]
Can you give the latest version a try? Updated the RN dependencies

**Comment by spencercarli** [comment]
Closing because it should be fixed now and I haven't heard anything else in a while
