### ISSUE TITLE
re render MeteorComplexListView based on a change in state.

### ISSUE THREAD

**Issue by sepehrooo** [spencercarli/react-native-meteor-boilerplate#38]
I have a MeteorComplexListView and I want to give dynamic styling to it's list items.
for example when a list item got touched, I want to give that specific list item a background color to show it is active.

I thought in renderRow I could do this:
`const style = this.state.itemId == item._id ? { color: 'red' } : {};`

```
return (
  <TouchableHighlight style={[styles.buttons, style]} onPress={() => {
    this.setState({ itemId: item._id })
    this.setState({ subitem: {} })
  }}>
    <Text>{item.text}</Text>
  </TouchableHighlight>
);
```

but this won't re render the listView and nothing happens.

Any ideas?

**Comment by spencercarli** [comment]
Hmm this all looks find to me. Could you post the full `renderRow` and the MeteorComplexListView? Wondering if `this` isn't bound correctly

**Comment by sepehrooo** [comment]
`import React, {Component} from 'react';
import { StyleSheet, Text, View, TouchableHighlight, Image } from 'react-native';
import Meteor from 'react-native-meteor';
import {MeteorListView, MeteorComplexListView} from 'react-native-meteor';
import {COLORS, GRID_SETTINGS} from '../../styles';
import config from '../../config';

let BASE_URL = config.BASE_URL;

class Items extends Component {
  constructor(props) {
    super(props);
    this.state = {
      itemId: '',
      subitem: {}
    };
    this.renderItem = this.renderItem.bind(this);
    this.renderSubitem = this.renderSubitem.bind(this);
  }
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.items}>
          <MeteorComplexListView
              elements={()=>{return Meteor.collection('items').find()}}
              renderRow={this.renderItem}
              enableEmptySections={true}
            />
        </View>
        <View style={styles.content}>
          <Image source={{uri: this.state.subitem.deviceImagePath}} style={styles.itemViewImage} >
            <View style={styles.subitems}>
              <MeteorComplexListView
                elements={()=>{return Meteor.collection('subitems').find({itemId: this.state.itemId})}}
                renderRow={this.renderSubitem}
                enableEmptySections={true}
              />
            </View>
            <View style={styles.itemView}>
              <View style={styles.itemDetails}>
                  <Text style={styles.subitemTitle}>{this.state.subitem.text}</Text>
                  <Text style={styles.subitemDesc}>{this.state.subitem.description}</Text>
              </View>  
            </View>
          </Image>
        </View>
      </View>);
  }
  renderItem(item) {
    const viewStyle = this.state.itemId && this.state.itemId == item._id ? styles.selected : styles.notSelected;
    return (
      <View style={viewStyle}>
        <TouchableHighlight style={[styles.buttons]} onPress={() => {
          this.setState({ itemId: item._id });
          this.setState({ subitem: {} });
        }}>
          <Text>{item.text}</Text>
        </TouchableHighlight>
      </View>
    );
  }
  renderSubitem(subitem) {
    return (
      <TouchableHighlight style={styles.buttons} onPress={() => {
        subitem.deviceImagePath = BASE_URL + subitem.imagePath;
        this.setState({ subitem: subitem });
      }}>
        <Text>{subitem.text}</Text>
      </TouchableHighlight>
    );
  }
  style() {
    return {
      backgroundColor: 'yellow'
    }
  }
}


const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row'
  },
  items: {
    flex: 2,
    backgroundColor: 'gray'
  },
  content: {
    flexDirection: 'row',
    flex: 10
  },
  subitems: {
    flex: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.8)'
  },
  itemView: {
    flex: 8,
  },
  selected: {
    backgroundColor: 'yellow'
  },
  notSelected: {
    backgroundColor: 'red'
  },
  itemDetails : {
    top: 20,
    right: 10,
    position: 'absolute',
  },
  itemViewImage: {
    flex: 1,
    backgroundColor: 'yellow',
    flexDirection: 'row'
  },
  subitemTitle: {
    textAlign: 'right',
    fontSize: 20,
    fontWeight: 'bold'
  },
  subitemDesc: {
    textAlign: 'right',
    fontSize: 15
  },
  buttons: {

  }
});


export default Items;`

**Comment by sepehrooo** [comment]
@spencercarli Thanks for responding.
Here's the whole items.js:
https://jsfiddle.net/b5doktjg/

**Comment by sepehrooo** [comment]
The thing is, I think ListViews only re-render when their dataSource changes.
These TouchableHighlights only render when at first the listview is initialized:
Here's a gif of my app as you can see I have 2 listViews and I want to give styles on the listItems that are selected and are active.

![untitled](https://cloud.githubusercontent.com/assets/2351478/17086191/252b0182-5201-11e6-9b63-088af1320615.gif)

**Comment by sepehrooo** [comment]
I've found a solution for others having this problem.
You can give ListView or MeteorComplexListView a key prop and when that key changes, the listView will re render.
`<MeteorComplexListView 
key={this.state.itemId} 
elements={()=>{return Meteor.collection('items').find()}}
renderRow={this.renderItem.bind(this)} 
/>` 

Whenever this.state.itemId changes the listView will re render.

Here's the result:
![salam](https://cloud.githubusercontent.com/assets/2351478/17172353/f12fd1f4-5409-11e6-8053-e2a92c88e90c.gif)
