### ISSUE TITLE
Android doesn't render login buttons

### ISSUE THREAD

**Issue by tdhz77** [spencercarli/react-native-meteor-boilerplate#4]
![rnonandroid](https://cloud.githubusercontent.com/assets/2060654/13500393/fe29a8f8-e127-11e5-834b-79e2af37256d.png)

I don't think this is what the app would look like on OSX. I don't have OSX right now to test. Can anybody confirm?

**Comment by spencercarli** [comment]
The lack of login buttons indicates that that the app didn't connect to the ddp server. I don't have experience with linux so I'm not sure if there is some other issue but two things to try:

1. Make sure the meteor server is running
2. Change `localhost` to your computer's IP address [here](https://github.com/spencercarli/react-native-meteor-boilerplate/blob/master/RNApp/app/config.js#L11)

**Comment by hakosl** [comment]
I have the same problem on Windows, I think that it is clear that ddpClient.connect is not working for me, when i log the error from ddpClient.connect it says: 
`failed to connect to localhost/127.0.0.1 (port 3000) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)`

**Comment by spencercarli** [comment]
@hakosl I don't have access to a windows machine and I'm not sure what RN support is like for Windows right now so everything I say is purely speculation but based on the error you posted did you try to replace `localhost` with your computers IP address? (i'm not sure how to get that on windows)

**Comment by josephdburdick** [comment]
@spencercarli I resolved this issue by creating a conditional that renders the buttons or returns a <Text> component saying it couldn't connect to the server. This wording could be changed a bit for the masses but it works to remind me when my IP address changes and no longer connects.

**Comment by hakosl** [comment]
@spencercarli When I replaced `localhost` with my Virtualbox IPv4-address I got it working.

**Comment by spencercarli** [comment]
Glad you got this sorted out! @josephdburdick good idea on rendering a different component when not connected to the server - tracking that task [here](https://github.com/spencercarli/react-native-meteor-boilerplate/issues/9)
