### ISSUE TITLE
Connecting to production server

### ISSUE THREAD

**Issue by elie222** [spencercarli/react-native-meteor-boilerplate#42]
How would you connect an app to a production server?

I changed this line:
`let METEOR_URL = 'ws://localhost:3000/websocket';`
to:
`let METEOR_URL = 'ws://example.com/websocket';`
But it didn't work for me.

Feel like I'm missing something small here.

**Comment by spencercarli** [comment]
If you want to connect to the production server you will want to change [this line](https://github.com/spencercarli/react-native-meteor-boilerplate/blob/master/RNApp/app/config/settings.js#L2) to something like `let METEOR_URL = 'ws://example.com/websocket';`

However, if the app has been build for deployment for the app stores you want to change [this line](https://github.com/spencercarli/react-native-meteor-boilerplate/blob/master/RNApp/app/config/settings.js#L4) to something like `let METEOR_URL = 'ws://example.com/websocket';`

**Comment by elie222** [comment]
I finally solved the problem, by writing:
`let METEOR_URL = 'wss://example.com/websocket';`

I had to use `wss`.
