### ISSUE TITLE
Running react-native run-ios always opens two windows

### ISSUE THREAD

**Issue by rootedsoftware** [spencercarli/react-native-meteor-boilerplate#47]
It always opens two http://localhost:8081/debugger-ui tabs in Chrome. Then the app crashes. If I close one of the tabs and reload the app everything is fine.

**Comment by spencercarli** [comment]
I've never seen this before. A few questions:
1. Are you developing for ios or android?
2. What if you close both tabs and then try to start the app - does it still open two?
3. What version of React Native are you using?

**Comment by rootedsoftware** [comment]
This morning I can't reproduce the problem. Strange, I had been just dealing with this issue for a while, now suddenly after I file the issue it disappears.. haha. 

Thanks
