### ISSUE TITLE
Cannot login when runing on iOS

### ISSUE THREAD

**Issue by ghost** [spencercarli/react-native-meteor-boilerplate#49]
I cloned the repo
followed the steps and I reach to the login page.
I can create a user, and I can see the user has been inserted into `meteor mongo`
however, after create user, it doesn't go to the profile page due to `meteor.user()` returns null.

Anyone has the same issue?

Thanks

**Comment by ghost** [comment]
nvm, you have to sign up with a valid email address, other wise, it will fail.

**Comment by spencercarli** [comment]
yeah it's not super intuitive - something I've considered changing
