### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by Jorrit2002** [spencercarli/react-native-meteor-boilerplate#50]
When running the code on an iOS device without any change in the code I get the following error:

```
 2016-08-22 17:21:16.243 [fatal][tid:main] 
Unhandled JS Exception: SyntaxError: Unexpected token '<'
```

any suggestions?

**Comment by spencercarli** [comment]
Hmm I've seen that before but can't remember under what circumstances. I'd say try to delete your node_modules and reinstall them.

Another option is to try the [`android-fix`](https://github.com/spencercarli/react-native-meteor-boilerplate/tree/android-fix) branch (even though you're asking about ios, there are some ios changes in that branch)

**Comment by Jorrit2002** [comment]
got it working after deleting everything and starting over. However, I still got this same problem in an other starter template.
