### ISSUE TITLE
Fetching data from database

### ISSUE THREAD

**Issue by Jorrit2002** [spencercarli/react-native-meteor-boilerplate#56]
Could someone explain how I fetch data from meteor?
In Details.js data is fetched but presented using the MeteorListView. I'd like to just print the fetched data in the console but I can't figure out how to do that. The handle doesn't contain any objects.

```
export default createContainer(() => {
  const handle = Meteor.subscribe('details-list');
  return {
    detailsReady: handle.ready(),
  };
}, DetailsContainer);
```

**Comment by spencercarli** [comment]
To publish the data in the console you could run `Meteor.collection('details').find()` which will return an array of objects once the subscription has completed.

Be sure to check out the [`react-native-meteor`](https://github.com/inProgress-team/react-native-meteor#react-native-meteor) docs for more info!
