### ISSUE TITLE
react-native run-ios build fail

### ISSUE THREAD

**Issue by xyx2011** [spencercarli/react-native-meteor-boilerplate#57]
Installing build/Build/Products/Debug-iphonesimulator/RNApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
RNApp/node_modules/react-native/node_modules/promise/lib/done.js:10
throw err;
^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by spencercarli** [comment]
Yargh! I need to update the boilerplate. In the mean time give [this](https://github.com/facebook/react-native/issues/8584#issuecomment-236366222) a shot. Not sure if that's the issue, but I know it's bitten me a few times lately.

**Comment by xyx2011** [comment]
@spencercarli Many thanks to you! I'll give it a shot.

**Comment by spencercarli** [comment]
Could you give the latest updates a shot?

**Comment by xyx2011** [comment]
the latest updates works! Thanks!!!
