### ISSUE TITLE
Can not start on android

### ISSUE THREAD

**Issue by s7dhansh** [spencercarli/react-native-meteor-boilerplate#58]
I have an emulator running via: 
`emulator -avd Nexus_5_API_23 -use-system-libs`

`react-native run-android`, or `gradlew installDebug` fails with the error 

> Starting JS server...
> Running /home/sudhanshu/Android/Sdk/platform-tools/adb reverse tcp:8081 tcp:8081
> Building and installing the app on the device (cd android && ./gradlew installDebug...
> Downloading https://services.gradle.org/distributions/gradle-2.4-all.zip
> 
> Exception in thread "main" java.lang.ExceptionInInitializerError
>         at javax.crypto.JceSecurityManager.<clinit>(java.base@9-Ubuntu/JceSecurityManager.java:65)
>         at javax.crypto.Cipher.getConfiguredPermission(java.base@9-Ubuntu/Cipher.java:2595)
>         at javax.crypto.Cipher.getMaxAllowedKeyLength(java.base@9-Ubuntu/Cipher.java:2619)
>         at sun.security.ssl.CipherSuite$BulkCipher.isUnlimited(java.base@9-Ubuntu/CipherSuite.java:602)
>         at sun.security.ssl.CipherSuite$BulkCipher.<init>(java.base@9-Ubuntu/CipherSuite.java:574)
>         at sun.security.ssl.CipherSuite$BulkCipher.<clinit>(java.base@9-Ubuntu/CipherSuite.java:460)
>         at sun.security.ssl.CipherSuite.<clinit>(java.base@9-Ubuntu/CipherSuite.java:1074)
>         at sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuiteList(java.base@9-Ubuntu/SSLContextImpl.java:353)
>         at sun.security.ssl.SSLContextImpl.access$100(java.base@9-Ubuntu/SSLContextImpl.java:41)
>         at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(java.base@9-Ubuntu/SSLContextImpl.java:582)
>         at java.lang.Class.forName0(java.base@9-Ubuntu/Native Method)
>         at java.lang.Class.forName(java.base@9-Ubuntu/Class.java:291)
>         at java.security.Provider$Service.getImplClass(java.base@9-Ubuntu/Provider.java:1844)
>         at java.security.Provider$Service.newInstance(java.base@9-Ubuntu/Provider.java:1820)
>         at sun.security.jca.GetInstance.getInstance(java.base@9-Ubuntu/GetInstance.java:236)
>         at sun.security.jca.GetInstance.getInstance(java.base@9-Ubuntu/GetInstance.java:164)
>         at javax.net.ssl.SSLContext.getInstance(java.base@9-Ubuntu/SSLContext.java:166)
>         at javax.net.ssl.SSLContext.getDefault(java.base@9-Ubuntu/SSLContext.java:98)
>         at javax.net.ssl.SSLSocketFactory.getDefault(java.base@9-Ubuntu/SSLSocketFactory.java:123)
>         at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(java.base@9-Ubuntu/HttpsURLConnection.java:332)
>         at javax.net.ssl.HttpsURLConnection.<init>(java.base@9-Ubuntu/HttpsURLConnection.java:289)
>         at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(java.base@9-Ubuntu/HttpsURLConnectionImpl.java:85)
>         at sun.net.www.protocol.https.Handler.openConnection(java.base@9-Ubuntu/Handler.java:62)
>         at sun.net.www.protocol.https.Handler.openConnection(java.base@9-Ubuntu/Handler.java:57)
>         at java.net.URL.openConnection(java.base@9-Ubuntu/URL.java:1049)
>         at org.gradle.wrapper.Download.downloadInternal(Download.java:55)
>         at org.gradle.wrapper.Download.download(Download.java:44)
>         at org.gradle.wrapper.Install$1.call(Install.java:59)
>         at org.gradle.wrapper.Install$1.call(Install.java:46)
>         at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
>         at org.gradle.wrapper.Install.createDist(Install.java:46)
>         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
>         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
>         at javax.crypto.JceSecurity.<clinit>(java.base@9-Ubuntu/JceSecurity.java:91)
>         ... 33 more
> Caused by: java.lang.NullPointerException
>         at sun.nio.fs.UnixPath.normalizeAndCheck(java.base@9-Ubuntu/UnixPath.java:75)
>         at sun.nio.fs.UnixPath.<init>(java.base@9-Ubuntu/UnixPath.java:69)
>         at sun.nio.fs.UnixFileSystem.getPath(java.base@9-Ubuntu/UnixFileSystem.java:280)
>         at java.nio.file.Paths.get(java.base@9-Ubuntu/Paths.java:84)
>         at javax.crypto.JceSecurity.setupJurisdictionPolicies(java.base@9-Ubuntu/JceSecurity.java:254)
>         at javax.crypto.JceSecurity.access$000(java.base@9-Ubuntu/JceSecurity.java:49)
>         at javax.crypto.JceSecurity$1.run(java.base@9-Ubuntu/JceSecurity.java:82)
>         at javax.crypto.JceSecurity$1.run(java.base@9-Ubuntu/JceSecurity.java:79)
>         at java.security.AccessController.doPrivileged(java.base@9-Ubuntu/Native Method)
>         at javax.crypto.JceSecurity.<clinit>(java.base@9-Ubuntu/JceSecurity.java:78)
>         ... 33 more
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/android-setup.html

`~/android-studio/gradle/gradle-2.14.1/bin/gradle installDebug` also fails with a different error

> A problem occurred configuring root project 'RNApp'.
> 
> > Could not resolve all dependencies for configuration ':classpath'.
> > Could not resolve com.android.tools.build:gradle:1.3.1.
> >      Required by:
> >          :RNApp:unspecified
> >       > Could not resolve com.android.tools.build:gradle:1.3.1.
> >          > java.lang.ExceptionInInitializerError
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Any help?

**Comment by spencercarli** [comment]
Not sure off the top of my head but I'm hoping to take some time to dive into this today. Will update if I find anything.

**Comment by spencercarli** [comment]
Can you give the latest updates a shot? Upgraded React Native to 0.35

**Comment by s7dhansh** [comment]
Doing an `npm install` in the latest updates fails with 

> 64 verbose stack Error: The package eslint-plugin-import@2.0.1 does not satisfy its siblings' peerDependencies requirements!
> 64 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:125:32
> 64 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:268:7
> 64 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
> 64 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
> 64 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
> 64 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
> 64 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
> 64 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
> 64 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
> 64 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
> 65 verbose cwd /home/sudhanshu/react-native-meteor-boilerplate/RNApp
> 66 error Linux 4.8.0-25-generic
> 67 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> 68 error node v4.6.0
> 69 error npm  v2.15.9
> 70 error code EPEERINVALID
> 71 error peerinvalid The package eslint-plugin-import@2.0.1 does not satisfy its siblings' peerDependencies requirements!
> 71 error peerinvalid Peer eslint-config-airbnb@12.0.0 wants eslint-plugin-import@^1.16.0
> 72 verbose exit [ 1, true ]

I think there is some version problem or something. If it helps, I am on Ubuntu 16.10.

Regarding the OP, I am still unable to figure out what exactly this refers to,

> Caused by: java.lang.NullPointerException
> at sun.nio.fs.UnixPath.normalizeAndCheck(java.base@9-Ubuntu/UnixPath.java:75)

I believe it to be the culprit.

**Comment by spencercarli** [comment]
Fixed the peerDependency issue. Not sure what's going on with Android though - I'm able to run it on a device without any issues. I don't have an emulator set up on my machine right now so I can try that route.

Have you used Geny Motion before? maybe give that a shot and see if you're running into the same issue

**Comment by s7dhansh** [comment]
Thank you.

Genymotion fails on 16.10 because of a newer libpango. I did not mess with it as it is a base for many system execs.

The new master gives a different error, may be because I shifted from openjdk to oracle one. The new error is: 

```
Could not determine java version from '9-ea'.
```

Any ideas on this new development?

**Comment by s7dhansh** [comment]
I guess the gradlew binary included in the app is quite an old one. This bug was fixed in v2.10 (https://discuss.gradle.org/t/gradle-cannot-parse-version-numbers-of-java-9-b96/13241/2).

> Using gradle v2.14 from was partial success, failing at this point:
> Failed to apply plugin [id 'com.android.application']
> 
> > Gradle version 2.2 is required. Current version is 2.14.1. If using the gradle wrapp
> > er, try editing the distributionUrl in /home/sudhanshu/react-native-meteor-boilerplate/RN
> > App/android/gradle/wrapper/gradle-wrapper.properties to gradle-2.2-all.zip

**Comment by spencercarli** [comment]
Hmm so is this an issue with React Native rather than this boilerplate specifically?

**Comment by pawelk** [comment]
I have encountered very similar problem.
Ubuntu 16.10, node 7.4, openjdk-9, React Native 0.40.0. 

Followed RN Getting Started instructions to the letter, everything went smoothly, the emulator is up and running, then:

> $react-native run-android
> Starting JS server...
> Running /home/pawel/Android/Sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
> Building and installing the app on the device (cd android && ./gradlew installDebug)...
> Downloading https://services.gradle.org/distributions/gradle-2.4-all.zip
> 
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at javax.crypto.JceSecurityManager.<clinit>(java.base@9-Ubuntu/JceSecurityManager.java:65)
> 	at javax.crypto.Cipher.getConfiguredPermission(java.base@9-Ubuntu/Cipher.java:2595)
> 	at javax.crypto.Cipher.getMaxAllowedKeyLength(java.base@9-Ubuntu/Cipher.java:2619)
> 	at sun.security.ssl.CipherSuite$BulkCipher.isUnlimited(java.base@9-Ubuntu/CipherSuite.java:602)
> 	at sun.security.ssl.CipherSuite$BulkCipher.<init>(java.base@9-Ubuntu/CipherSuite.java:574)
> 	at sun.security.ssl.CipherSuite$BulkCipher.<clinit>(java.base@9-Ubuntu/CipherSuite.java:460)
> 	at sun.security.ssl.CipherSuite.<clinit>(java.base@9-Ubuntu/CipherSuite.java:1074)
> 	at sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuiteList(java.base@9-Ubuntu/SSLContextImpl.java:353)
> 	at sun.security.ssl.SSLContextImpl.access$100(java.base@9-Ubuntu/SSLContextImpl.java:41)
> 	at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(java.base@9-Ubuntu/SSLContextImpl.java:582)
> 	at java.lang.Class.forName0(java.base@9-Ubuntu/Native Method)
> 	at java.lang.Class.forName(java.base@9-Ubuntu/Class.java:291)
> 	at java.security.Provider$Service.getImplClass(java.base@9-Ubuntu/Provider.java:1844)
> 	at java.security.Provider$Service.newInstance(java.base@9-Ubuntu/Provider.java:1820)
> 	at sun.security.jca.GetInstance.getInstance(java.base@9-Ubuntu/GetInstance.java:236)
> 	at sun.security.jca.GetInstance.getInstance(java.base@9-Ubuntu/GetInstance.java:164)
> 	at javax.net.ssl.SSLContext.getInstance(java.base@9-Ubuntu/SSLContext.java:166)
> 	at javax.net.ssl.SSLContext.getDefault(java.base@9-Ubuntu/SSLContext.java:98)
> 	at javax.net.ssl.SSLSocketFactory.getDefault(java.base@9-Ubuntu/SSLSocketFactory.java:123)
> 	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(java.base@9-Ubuntu/HttpsURLConnection.java:332)
> 	at javax.net.ssl.HttpsURLConnection.<init>(java.base@9-Ubuntu/HttpsURLConnection.java:289)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(java.base@9-Ubuntu/HttpsURLConnectionImpl.java:85)
> 	at sun.net.www.protocol.https.Handler.openConnection(java.base@9-Ubuntu/Handler.java:62)
> 	at sun.net.www.protocol.https.Handler.openConnection(java.base@9-Ubuntu/Handler.java:57)
> 	at java.net.URL.openConnection(java.base@9-Ubuntu/URL.java:1049)
> 	at org.gradle.wrapper.Download.downloadInternal(Download.java:55)
> 	at org.gradle.wrapper.Download.download(Download.java:44)
> 	at org.gradle.wrapper.Install$1.call(Install.java:59)
> 	at org.gradle.wrapper.Install$1.call(Install.java:46)
> 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> 	at org.gradle.wrapper.Install.createDist(Install.java:46)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
> 	at javax.crypto.JceSecurity.<clinit>(java.base@9-Ubuntu/JceSecurity.java:91)
> 	... 33 more
> Caused by: java.lang.NullPointerException
> 	at sun.nio.fs.UnixPath.normalizeAndCheck(java.base@9-Ubuntu/UnixPath.java:75)
> 	at sun.nio.fs.UnixPath.<init>(java.base@9-Ubuntu/UnixPath.java:69)
> 	at sun.nio.fs.UnixFileSystem.getPath(java.base@9-Ubuntu/UnixFileSystem.java:280)
> 	at java.nio.file.Paths.get(java.base@9-Ubuntu/Paths.java:84)
> 	at javax.crypto.JceSecurity.setupJurisdictionPolicies(java.base@9-Ubuntu/JceSecurity.java:254)
> 	at javax.crypto.JceSecurity.access$000(java.base@9-Ubuntu/JceSecurity.java:49)
> 	at javax.crypto.JceSecurity$1.run(java.base@9-Ubuntu/JceSecurity.java:82)
> 	at javax.crypto.JceSecurity$1.run(java.base@9-Ubuntu/JceSecurity.java:79)
> 	at java.security.AccessController.doPrivileged(java.base@9-Ubuntu/Native Method)
> 	at javax.crypto.JceSecurity.<clinit>(java.base@9-Ubuntu/JceSecurity.java:78)
> 	... 33 more
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/android-setup.html
> 
> (node:7263) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined
> (node:7263) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pawelk** [comment]
FWIW I had a very similar problem with a React Native app created by following the RN Getting Started guide. On Ubuntu 16.10, node 7.4, RN 0.40, openjdk-9. 

Installing openjdk-8 and setting it as the default Java version fixed it. It looks like the problem are security policy files which missing in Java 9 (being replaced by java.security config file), but I guess javax.crypto.JceSecurity expects these files to be there.

**Comment by XertroV** [comment]
@pawelk's suggestion worked for me.

Particularly:

```
sudo apt install openjdk-8-jdk-headless
update-java-alternatives --list
sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
```

Edit: though now I see this is an issue on `react-native-meteor-boilerplate`. Like pawelk I had this issue on the RN Getting Started guide, ubuntu 16.10

**Comment by consentsam** [comment]
Whenever I run `react-native run-android`
I am getting this error 
I have gone through the above process suggested by maotara but i am still facing the problem.
When I run this command `echo $JAVA_HOME`
i get the path of my jdk so thats not the problem.
Please help me !!

**Error Message**
Scanning 557 folders for symlinks in /root/w/node_modules (3ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Downloading https://services.gradle.org/distributions/gradle-2.14.1-all.zip

Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:59)
	at org.gradle.wrapper.Install$1.call(Install.java:46)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
