### ISSUE TITLE
App doesn't get past loading spinner

### ISSUE THREAD

**Issue by kyleburris** [spencercarli/react-native-meteor-boilerplate#59]
I'm able to launch the app both in a simulator on my Nexus 5, but all I see is a white screen with the loading spinner, I can leave it for a long time and it never passes it. Any ideas?

**Comment by spencercarli** [comment]
Two things
1. Is the Meteor app running?
2. Did you change `localhost` to your machine's ip address ([instructions](https://github.com/spencercarli/react-native-meteor-boilerplate#running-on-android-device))

**Comment by kyleburris** [comment]
I didn't have the meteor app running, since that wasn't part of the instructions for running on android. 

Anyways that did the trick and it all works now. Thanks for responding so quickly
