### ISSUE TITLE
Can not start app on simulation

### ISSUE THREAD

**Issue by nguyenhose** [spencercarli/react-native-meteor-boilerplate#60]
I got this error message when start react native 

`ERROR  watch null EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch null","filename":null}
Error: watch null EMFILE
    at exports._errnoException (util.js:855:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21`

I installed watchman and already running server, but still got the problem. Please help.

Note: Seem it's error when using Mac OS Sierra. Please closed it =) 

https://github.com/facebook/react-native/issues/9309

For who got problem with it:
- Update Xcode 8
- `brew install/update watchman`

**Comment by spencercarli** [comment]
Hey I'm sorry I never responded to this. Slipped through the cracks. Glad you got it working.
