### ISSUE TITLE
Connect to iphone and get a white screen with the loading spinner

### ISSUE THREAD

**Issue by ghost** [spencercarli/react-native-meteor-boilerplate#61]
I keep getting a white screen with the loading spinner when I connect to an iphone. I could not figure out how to change from localhost to my machine's IP address in AppDelegate.m.
 
"In RNApp/ios/RNApp/AppDelegate.m change localhost to your machine's IP address"

**Comment by spencercarli** [comment]
You can run `ipconfig getifaddr en1` in terminal to get your IP address. 

Also make sure that your Meteor server is running.

**Comment by devfordays** [comment]
@spencercarli First off thank you for the boilerplate :) Amazing! But I am am getting the same problem & am little confused by the directions.

Be sure your Meteor app is running: In the MeteorApp directory, type meteor - **Check**
Get the IP address of your machine (you can run ipconfig getifaddr en1 to do so)  **Check**
In RNApp/ios/RNApp/AppDelegate.m change localhost to your machine's IP address **Out of the box there is no localhost config in this file so don't understand what to change ?**
In RNApp/app/config/settings.js change localhost to your machine's IP address
**Check - I was even able to hit the meteor app from the ios device using this ip address**
Plug your device into your computer (make sure it's on the same network) **Check**
Open the project in Xcode **Check**
Select your device in Xcode and press "Build and run" **Check**

**Comment by spencercarli** [comment]
Ah, that's changed in recent versions of React Native. I'll update the instructions.
