### ISSUE TITLE
Meteor Login Logic creates a weird issue for me

### ISSUE THREAD

**Issue by kevando** [spencercarli/react-native-meteor-boilerplate#62]
The condition at react-native-meteor-boilerplate/RNApp/app/index.js

```
if (status.connected === false || loggingIn) {
    return <Loading />;
  } else if (user !== null) {
    return <LoggedIn />;
  }
  return <LoggedOut />;
};
```

I get a weird issue where the user is authenticated, but the user object is null for a split second and the login screen flashes. Any idea how to fix this?

**Comment by kevando** [comment]
I was also thinking if it would make sense to save a 'authStatus' with AsyncStorage so that this conditional can fire much quicker in the event the login status a few seconds. Would that make sense?

**Comment by kevando** [comment]
I foolishly used AND operator on the first logic statement -_- Changed it to an OR and it works great. Thanks again for this dope repo!

**Comment by spencercarli** [comment]
Doh! Glad you got it sorted out
