### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by JulianKingman** [spencercarli/react-native-meteor-boilerplate#63]
Hi @spencercarli , I want to use this for a client project, but I couldn't find a license anywhere?
Thanks for being a react-native/meteor trailblazer!

**Comment by spencercarli** [comment]
Whoops, didn't realize this didn't have one. Sorry about that.

I just added the MIT license - I _think_ it's the most open one.

**Comment by JulianKingman** [comment]
Awesome, thanks 👍
