### ISSUE TITLE
Permission react-native-meteor

### ISSUE THREAD

**Issue by sabativi** [spencercarli/react-native-meteor-boilerplate#64]
Hey,

It is written on the react native meteor project [install doc](https://github.com/inProgress-team/react-native-meteor/blob/master/docs/Install.md) that one should add : 

`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`

to the manifest. @spencercarli you did not use it, is there any reason ?

**Comment by spencercarli** [comment]
I think that was added after I made the last updates. Hoping to do a series of updates to this repo soon. Would definitely suggest adding that permission to the manifest though!

**Comment by spencercarli** [comment]
Closed via #65
