### ISSUE TITLE
Best way to change bottom tabs based on current screen?

### ISSUE THREAD

**Issue by acomito** [spencercarli/react-native-meteor-boilerplate#66]
Given react-native-meteor-boilerplate's setup, is there a best practice for changing the bottom tabs based on the current path/route?

Can/should this be handles in config/routes.js or in the layout component with some if/then logic?

**Comment by spencercarli** [comment]
Hey @acomito - sorry about the delay in my response. I'm hoping to update this boilerplate very soon. Primarily for the routing/tabs. I'll be using [react-navigation](https://github.com/react-community/react-navigation) to replace it.

**Comment by acomito** [comment]
Okay. Is react-navigation the safest bet out of the great navigation war of 2016?

**Comment by spencercarli** [comment]
I'll tell ya at the end of the year 😉 

I'm pretty confident in it though - community supported, successor to ex-navigation, strong pickup, etc. I'm [updating my course](http://learn.handlebarlabs.com/p/react-native-meteor) to use it though, so I'm pretty confident in it.

**Comment by acomito** [comment]
> I'm pretty confident in it though - community supported, successor to ex-navigation, strong pickup, etc. I'm updating my course to use it though, so I'm pretty confident in it.

I've been toying around with it this last week. So far, it's my favorite router-- super straightforward.
