### ISSUE TITLE
Sharing code between the client and the server

### ISSUE THREAD

**Issue by asafshen** [spencercarli/react-native-meteor-boilerplate#67]
Is there any recommended way to share code between the client(`RNApp`) and the server(`MeteorApp`) ?

Maybe it is possible to access `MeteorApp` shared content (i.e. anything that is not in 'server' or 'private' directories)  from `RNApp`?

Thanks

**Comment by spencercarli** [comment]
Unfortunately I haven't found a great pattern for it yet (though I haven't given it much effort). What kind of code are you looking to share?
