### ISSUE TITLE
Where to hide splash screen ?

### ISSUE THREAD

**Issue by sabativi** [spencercarli/react-native-meteor-boilerplate#69]
Hello,

I was wondering where do you guys put the `splashscreen.hide()` instructions inside this boilerplate.
Because il the user was connected but killed the app, we want him to see only the loggedIn layout when he goes back.
Because of reactivity and depending on network, when putting see on `componentDidMount` method in RNApp component, I see first the LoggedOut layout and then the the user is loggedIn by meteor so it goes automatically to the loggedIn layout.

Thanks for your tips

**Comment by spencercarli** [comment]
Hmm splashscreen.hide seems to be a cordova/phonepage thing, right?

I'm about to update the boilerplate to (hopefully) fix the issue you described!

**Comment by sabativi** [comment]
I am using https://github.com/crazycodeboy/react-native-splash-screen
