### ISSUE TITLE
Need help with the ddp.subscribe

### ISSUE THREAD

**Issue by sepehrooo** [spencercarli/react-native-meteor-boilerplate#7]
Hi, 
First thank you for your awesome boilerplate :) 
I am trying to subscribe to my meteor mongo collection, but I keep getting this error:

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

In signin.js I have this code:

handleSignIn() {
    if (this.validInput()) {
      ddpClient.loginWithUsername(this.state.username, this.state.password, (error, res) => {
        if (error) {
          this.setState({error: error.reason})
        } else {
          this.props.changedSignedIn(true);
          this.subscribeToItems();
        }
      });
    }
  }
subscribeToItems() {
    let itemsPromise = false;
    let self = this;
    itemsPromise = ddpClient.subscribePromise('items');
    itemsPromise.then(function(result){
      if (result === true) {
         self.setState({items: ddpClient.collections.items});
      } else {
        console.log(result);
      }
    }, function(reason) {
      console.log(reason);
    });
  }

Am I doing something wrong?
I would really appreciate it if you could point me in the right direction.

**Comment by spencercarli** [comment]
`signIn.js` is unmounted when a user successfully signs in. So you would want to put `subscribeToItems` in `signedOut.js` instead.

**Comment by sepehrooo** [comment]
Oh I see! Thanks a lot :)
