### ISSUE TITLE
Failing in simulation with TransformError

### ISSUE THREAD

**Issue by TimoRuetten** [spencercarli/react-native-meteor-boilerplate#71]
When start the simulation I get this error:

TransformError: /...../RNApp/index.ios.js: Couldn't find preset "es2015" relative to directory: ....

I searched for this problem and ended up in another issue with a "solution". The solution does not work for me - maybe the problem is related to smth else ?

https://github.com/laravel/elixir/issues/354

**Comment by TimoRuetten** [comment]
I've fixed it by doing this:


Add these 2 packages:
babel-preset-es2015
babel-preset-react

Add this to package.json:
"babel": {
    "presets": [
      "es2015",
      "react"
    ]
  }

**Comment by spencercarli** [comment]
Thanks for bringing this up. I'll look into it more soon.
