### ISSUE TITLE
Thoughts on new "Meteor Client Bundler" vs react-native-meteor?

### ISSUE THREAD

**Issue by acomito** [spencercarli/react-native-meteor-boilerplate#73]
So far react-native-meteor covers anything that I would need, but have you seen this and what are your thoughts?

https://blog.meteor.com/leverage-the-power-of-meteor-with-any-client-side-framework-bfb909141008#.80ewjbj87

**Comment by spencercarli** [comment]
Looks awesome! Planning to give it a shot this week and will drop more notes then! 😄
