### ISSUE TITLE
check ddp server conection

### ISSUE THREAD

**Issue by ketankulkarni** [spencercarli/react-native-meteor-boilerplate#77]
while following steps to integrate react native and meteor from https://medium.com/differential/connecting-react-native-and-meteor-cccdb0df29e3  
there is instruction to check connection with DDP server  
So how to check DDP server connection

**Comment by spencercarli** [comment]
You'll see some information in the console when you turn on remote debugging for the React Native app. Something along the lines of "DDP is..."
