### ISSUE TITLE
Unable to resolve module react-native/Libraries/Renderer/shims/ReactNative ...

### ISSUE THREAD

**Issue by nicholaspsmith** [spencercarli/react-native-meteor-boilerplate#79]
Whenever I try to run the RNApp on ios after npm installing I get this error.

Steps to reproduce:
clone repository
cd into meteor app
`npm install && meteor`
cd into RNApp
`npm install && react-native run-ios`

Full error:
Unable to resolve module react-native/Libraries/Renderer/shims/ReactNative from /Users/nick/Desktop/react-native-meteor-boilerplate/RNApp/node_modules/react-native-meteor/src/Data.js: Module does not exist in the module map or in these directories:
  /Users/nick/Desktop/react-native-meteor-boilerplate/RNApp/node_modules/react-native/Libraries/Renderer/shims

**Comment by nloui** [comment]
Getting the same error

**Comment by nloui** [comment]
FWIW, I believe I resolved this by upgrading react native to the newest version using react-native-git-upgrade

**Comment by nicholaspsmith** [comment]
Yes. It was a dependency issue. Couldn't get it fixed just by upgrading RN to newest though.

I actually fixed it by using yarn instead of npm!

**Comment by DylanRichardPearson** [comment]
@nicholaspsmith could you explain further how you used yarn to fix it? I did a 'yarn install' and am still having this same issue.

**Comment by spencercarli** [comment]
I gotta go through and update this! Glad you got it working. Did you have to change anything other than doing `yarn install` instead of `npm install`?

**Comment by nicholaspsmith** [comment]
Delete `package.json.lock`

delete node modules `rm -rf node_modules`

then `yarn install`

Also make sure you are following the compatibility notes:

> Since RN 0.26.0 you have to use ws or wss protocol to connect to your meteor server. http is not working on Android.
It is recommended to always use the latest version of react-native-meteor compatible with your RN version.
For RN 0.45.x use version 1.0.6 of 'react-native-meteor'
For RN pre 0.45.x you can use version 1.0.3 in case or problems.
For RN > 0.45 you can use 1.1.x

**Comment by drpears** [comment]
@nicholaspsmith Unfortunately that doesn't fix it for me. I've tried it on multiple machines.

**Comment by nicholaspsmith** [comment]
I feel your pain. Also make sure to clear watchman watches `watchman watch-del-all`
reset packager cache `npm start -- --reset-cache`
And just keep deleting node modules and trying different versions of the react-native-meteor package.

If you wanted to post a link to your package.json I could compare it to mine.
