### ISSUE TITLE
App crashes in Xcode

### ISSUE THREAD

**Issue by derwaldgeist** [spencercarli/react-native-meteor-boilerplate#80]
Thank you for building this boilerplate. I really appreciate the work you put into this.

Just some stuff I stumbled upon and should be updated in the docs:
- Meteor requires to `npm install` before running `meteor`
- `react-native run ios` threw an error message on the popup terminal window
- `npm run ios` did not worked either, there is no such script in `package.json`.

I could start the app using Xcode. However, it only showed the launch screen and threw this error message after a while:

```
'NSInternalInconsistencyException', reason: 'bundleURL must be non-nil when not implementing loadSourceForBridge'
*** First throw call stack:
(0x18dc4afe0 0x18c6ac538 0x18dc4aeb4 0x18e6e37cc 0x1001427bc 0x100140a8c 0x100177ab0 0x100176cf8 0x100176ad8 0x1000e2d90 0x1000cc7a8 0x193de6e48 0x193ff337c 0x193ff8e24 0x19400d8b0 0x193ff60b8 0x18f7f4884 0x18f7f46f0 0x18f7f4aa0 0x18dbf942c 0x18dbf8d9c 0x18dbf69a8 0x18db26da4 0x193ddffc8 0x193ddac9c 0x1000ccb88 0x18cb3559c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

I can also see a type conversion warning in Xcode (I'm using 8.3.3):

![error](https://user-images.githubusercontent.com/3984535/28876006-f3a08066-7797-11e7-9b56-b8041b77f85c.png)

Is there anything else you one has to do besides setting the IP address in the settings.js file?

**Comment by spencercarli** [comment]
Thanks for bringing these points up! Sorry you're running into issues. I haven't updated this in quite a while so some packages could be out of date. It's on my todo list to update this boilerplate this week.

**Comment by spencercarli** [comment]
All of this should be fixed in the latest update!

**Comment by derwaldgeist** [comment]
Thanks!
